name: CI - Java Spring Boot # Nombre descriptivo del workflow

# Eventos que disparan el workflow
on:
  push:
     branches: [main, develop] # Cada push a main o develop
  pull_request:
     branches: [main, develop] # Cada PR hacia main o develop

# Conjuntos de pasos para construir y testear la app
jobs:
  build:

     runs-on: ubuntu-latest # El agente donde se ejecuta el workflow

     steps: 
     - name: Checkout repository
       uses: actions/checkout@v3
       # Clona tu repo para trabajar sobre el codigo

     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
      # Configura java 17 en el runner

     - name: Cache Maven packages
       uses: actions/cache@v3
       with:
         path: ~/.m2/repository
         key:  ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-maven-
         # Cache para acelerar descarga de dependencia Maven

     - name: Build and Test with Maven
       run: mvn clean verify
       # Compila y corre todas las pruebas unitarias
    
     - name: SonarCloud Scan
       uses: sonarsource/sonarcloud-github-action@master
       with:
         projectkey: emmanuel30412
         organization: Emmanuel30412
         token: ${{ secrets.SONAR_TOKEN }}      
